### PR TITLE
Catch ArgumentOutOfRangeException to fix issue #138

### PR DESCRIPTION
**Pull request by PatPeter**
If I ever `screen -r` into my server, I will almost always get the output in issue #138 and it will cause all four of my servers to crash. I cannot local admin my server because of this bug.

I built MultiAdmin.exe and tested it on my local, but I wasn't able to reproduce whatever causes this cursor error.

### CODE REVIEW

**Comment by Grover-c13** [comment]
Fix the formatting please

**Comment by SlenderPlays** [comment]
Putting it in a try catch block can  prevent things from crashing horribly, but I wouldn't call it fixed. Anyway, as Grover mentioned, fix the formatting, check Visual Studio settings, and if you do not manage to fix it, edit it manually in notepad++ and update/re-send the pull request.

**Comment by PatPeter** [comment]
Wow. Already, I'm off to a bad start with Visual Studio 2017 (last version of VS I had was incompatible with MA/SM so I installed VS2017 last night). It used spaces instead of tabs in a file that's **only** indented with tabs? Even Eclipse is better than that (I know, I just tested in an empty workspace).

And Notepad++? I guess I can't complain about Microsoft being space purists when I'm [a Notepad2 purist](http://www.flos-freeware.ch/notepad2.html) lol. Anyway, I just pushed a commit and I think it's showing in the pull request.

**Comment by PatPeter** [comment]
@Grover-c13 Alright. I compiled and uploaded my copy of MultiAdmin.exe to my production server and I have really good news but also bad news. The good news: this bug doesn't crash **all four** of my servers anymore! 60 people were spared a server-wide crash.

The bad news: the bug still occurs on certain servers and if it does, it crashes the server and takes it off the master server list.

If I understand the code completely in #138, could the buffer height of the console be fetched and then the CursorTop compared to the buffer height?

**Comment by Grover-c13** [comment]
"The bad news: the bug still occurs on certain servers and if it does, it crashes the server and takes it off the master server list." Lets try to get a more full solution then

Also are you sure this error isnt coming from OutputThread.cs where some cusor fuckery goes on to get the input line at the bottom? Your catch is only catching when we write a message to console

**Comment by PatPeter** [comment]
According to the stack trace it seems to be coming from the OutputThread: `at MultiAdmin.OutputThread.Read (MultiAdmin.MultiAdmin.Server server) [0x005fd] in :0`

However, if you look through OutputThread, the `height` parameter is never being set. It seems that `Console.CursorTop` must somehow be getting set to a negative value (which should be impossible) and adding 0 to a negative value does nothing to fix it.

**Comment by Grover-c13** [comment]
height is passed in as a default parameter of 0, it can be specified but it doesnt need to. We have one place where its set to -1:
https://github.com/Grover-c13/MultiAdmin/blob/master/mutliadmin/MultiAdmin/InputThread.cs#L28

server.Write(">>> " + message, ConsoleColor.DarkMagenta, -1); in InputThread.cs

So if CursorTop is at 0, it will end up being -1 when it goes to write the >>> "Input" line. We do kind of want it to be -1 from the top though because we want that line to be below that. Im guessing theres an instance when you connect to putty CursorTop is set to 0 or something and it errors out. Maybe just try modifying the ternary to be:

Console.CursorTop += (Console.CursorTop <= 0 || height < 0) ? 0 : height;

**Comment by Grover-c13** [comment]
Might be the buffer height property, another fix might be trying to increment it by 1

**Comment by Grover-c13** [comment]
Ready to merge?

**Comment by PatPeter** [comment]
@Grover-c13 You read my mind. The code as it is now is working stupendously. It's been running for over 36 hours on my server and not once have I seen the exception.

**Pull request merged**
